steps:

- id: "Rodando testes"
  name: 'gcr.io/cloud-builders/go'
  args:
  - 'test'
  - './src'

- id: "Build da imagem"
  name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/codeeducation-ci-go'
  - .

images:
  - gcr.io/$PROJECT_ID/codeeducation-ci-go
